services:
  daloradius-ibmhu:
    image: daloradius-ibmhu:latest
    container_name: daloradius-ibmhu
    restart: always
    depends_on: 
      - "daloradius-ibmhu-mariadb"
    ports:
      - '1812:1812/udp'
      - '1813:1813/udp'
      - '8008:80'
    environment:
      - MYSQL_HOST=daloradius-ibmhu-mariadb
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=xxYYaa1@
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKERDATA}/daloradius-ibmhu/freeradius/clients.conf:/etc/freeradius/3.0/clients.conf
  daloradius-ibmhu-mariadb:
    image: mariadb:10.3
    container_name: daloradius-ibmhu-mariadb
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=radius
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=xxYYaa1@
      - MYSQL_ROOT_PASSWORD=Ibm1kfT@
    volumes:
      - ${DOCKERDATA}/daloradius-ibmhu/mariadb:/var/lib/mysql
